INSERT INTO orders (total_price, order_status) VALUES
                                                   (100.50, 'PENDING'),
                                                   (250.75, 'CONFIRMED'),
                                                   (499.99, 'CANCELLED'),
                                                   (1200.00, 'CONFIRMED'),
                                                   (89.90, 'PENDING'),
                                                   (349.49, 'CONFIRMED'),
                                                   (999.99, 'CANCELLED'),
                                                   (150.00, 'PENDING'),
                                                   (75.25, 'CONFIRMED'),
                                                   (560.80, 'PENDING'),
                                                   (220.40, 'CANCELLED'),
                                                   (799.99, 'CONFIRMED'),
                                                   (134.60, 'CONFIRMED'),
                                                   (420.00, 'PENDING'),
                                                   (310.10, 'CANCELLED');

INSERT INTO order_item (order_id, product_id, quantity) VALUES
                                                            (1, 1, 2),
                                                            (1, 3, 1),
                                                            (2, 2, 1),
                                                            (2, 5, 2),
                                                            (3, 4, 1),
                                                            (3, 6, 3),
                                                            (4, 1, 1),
                                                            (4, 7, 2),
                                                            (5, 8, 1),
                                                            (6, 2, 2),
                                                            (6, 9, 1),
                                                            (7, 10, 1),
                                                            (8, 3, 2),
                                                            (9, 4, 1),
                                                            (10, 5, 3),
                                                            (11, 6, 1),
                                                            (12, 7, 2),
                                                            (13, 8, 1),
                                                            (14, 9, 2),
                                                            (15, 10, 1);